In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.impute import KNNImputer
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
data = pd.read_csv(r"C:\Users\anjal\Downloads\TNBC_data.csv")

In [3]:
data

,Gene ID,221NC,235NC,241NC,257NC,291NC,293NC,254NC,302NC,221TC,235TC,241TC,254TC,257TC,293TC,291TC,302TC,QCPool1,QCPool2,QCPool3
0,NCLN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DNAJC9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CRK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2696100.0,3043200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GPD1L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8647000.0,NaN,NaN,NaN,NaN,84432000.0,NaN,10741000.0
4,MTA1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2621,CACYBP,14809000.0,NaN,NaN,1992500.0,NaN,2794200.0,NaN,NaN,NaN,12168000.0,15569000.0,116690000.0,14214000.0,NaN,6970400.0,14675000.0,10743000.0,9872000.0,6774500.0
2622,RRBP1,282620.0,NaN,NaN,81933.0,NaN,549500.0,256490.0,NaN,759750.0,40872000.0,16161000.0,38284000.0,40373000.0,7365200.0,5942800.0,50443000.0,25160000.0,20392000.0,13413000.0
2623,PA2G4,3906500.0,NaN,NaN,NaN,NaN,1133400.0,NaN,NaN,NaN,4843300.0,11930000.0,54184000.0,2362600.0,NaN,NaN,10198000.0,20240000.0,NaN,749070.0
2624,TLN1,11239000.0,1373900.0,11466000.0,4082100.0,465420.0,11231000.0,3120700.0,1050400.0,2372000.0,21619000.0,27187000.0,28419000.0,26019000.0,10401000.0,17168000.0,27104000.0,181330000.0,52296000.0,11927000.0
2625,EMILIN1,NaN,NaN,828640.0,221660.0,NaN,NaN,1887300.0,4173800.0,3720600.0,14283000.0,7319700.0,16997000.0,47643000.0,44325000.0,8806700.0,10986000.0,67006000.0,31010000.0,9103100.0

In [4]:
data.shape

(2626, 20)

In [5]:
df=pd.DataFrame(data)
#  select columns that are not 'Gene ID'
value_columns = df.columns.difference(['Gene ID', 'QCPool1', 'QCPool2', 'QCPool3'])

# Initialize an empty dictionary to store counts for different cutoffs
count_dict = {}

# Iterate over different cutoff values and store counts
for cutoff in range(1, len(value_columns) + 1):
    non_nan_count_TC = df[[col for col in value_columns if "TC" in col]].count(axis=1)
    non_nan_count_NC = df[[col for col in value_columns if "NC" in col]].count(axis=1)
    rows_to_keep = (non_nan_count_TC >= cutoff) | (non_nan_count_NC >= cutoff)
    count_dict[cutoff] = sum(rows_to_keep)

# Create a DataFrame from the count dictionary
count_table = pd.DataFrame(count_dict.items(), columns=['TC and NC Cutoff', 'Protein Count'])

# Display the count table
print(count_table)

    TC and NC Cutoff  Protein Count
0                  1           2227
1                  2           2004
2                  3           1753
3                  4           1505
4                  5           1263
5                  6           1012
6                  7            772
7                  8            528
8                  9              0
9                 10              0
10                11              0
11                12              0
12                13              0
13                14              0
14                15              0
15                16              0

In [6]:
# Initialize an empty dictionary to store counts for different cutoffs
count_dict = {}

# Iterate over different cutoff values and store counts
for cutoff in range(1, len(value_columns) + 1):
    non_nan_count_TC = df[[col for col in value_columns if "TC" in col]].count(axis=1)
    non_nan_count_NC = df[[col for col in value_columns if "NC" in col]].count(axis=1)
    rows_to_keep = (non_nan_count_TC >= cutoff) 
    count_dict[cutoff] = sum(rows_to_keep)

# Create a DataFrame from the count dictionary
count_table = pd.DataFrame(count_dict.items(), columns=['TC Cutoff', 'Protein Count'])

# Display the count table
print(count_table)

    TC Cutoff  Protein Count
0           1           2180
1           2           1940
2           3           1691
3           4           1459
4           5           1212
5           6            965
6           7            734
7           8            501
8           9              0
9          10              0
10         11              0
11         12              0
12         13              0
13         14              0
14         15              0
15         16              0

In [7]:
# Initialize an empty dictionary to store counts for different cutoffs
count_dict = {}

# Iterate over different cutoff values and store counts
for cutoff in range(1, len(value_columns) + 1):
    non_nan_count_TC = df[[col for col in value_columns if "TC" in col]].count(axis=1)
    non_nan_count_NC = df[[col for col in value_columns if "NC" in col]].count(axis=1)
    rows_to_keep = (non_nan_count_NC >= cutoff)
    count_dict[cutoff] = sum(rows_to_keep)

# Create a DataFrame from the count dictionary
count_table = pd.DataFrame(count_dict.items(), columns=['NC Cutoff', 'Protein Count'])

# Display the count table
print(count_table)

    NC Cutoff  Protein Count
0           1           1559
1           2           1147
2           3            859
3           4            677
4           5            528
5           6            404
6           7            307
7           8            195
8           9              0
9          10              0
10         11              0
11         12              0
12         13              0
13         14              0
14         15              0
15         16              0

In [8]:
# Count the number of non-NaN values for each row in TC and NC columns
non_nan_count_TC = df[[col for col in value_columns if "TC" in col]].count(axis=1)
non_nan_count_NC = df[[col for col in value_columns if "NC" in col]].count(axis=1)

# Identify rows with at least 6 non-NaN entries in TC or NC columns
rows_to_keep = (non_nan_count_TC >= 6) | (non_nan_count_NC >= 6)

# Filter rows
retain_df = df[rows_to_keep]

In [9]:
retain_df = retain_df.set_index('Gene ID').T
retain_df = retain_df.drop(['QCPool1', 'QCPool2', 'QCPool3'])
retain_df

Gene ID,WFDC3,GPNMB,SAE1,YP015,GCDH,PPP1R12A,UTS2,USP29,IGLV3-19,CROCC,...,SERBP1,KHSRP,PLIN4,PARK7,COL12A1,ACO2,CACYBP,RRBP1,TLN1,EMILIN1
221NC,NaN,10854000.0,3725500.0,15431000.0,12694000.0,2587100.0,31090000.0,141350000.0,5217900.0,NaN,...,12371000.0,10178000.0,152560000.0,53250000.0,NaN,474750.0,14809000.0,282620.0,11239000.0,NaN
235NC,127000000.0,NaN,1532000.0,16334000.0,19338000.0,1095900.0,17627000.0,11587000.0,NaN,NaN,...,583440.0,NaN,83515000.0,10825000.0,NaN,NaN,NaN,NaN,1373900.0,NaN
241NC,16615000.0,NaN,1293500.0,10241000.0,8157200.0,988680.0,9646800.0,51832000.0,23535000.0,NaN,...,NaN,NaN,42868000.0,16012000.0,NaN,NaN,NaN,NaN,11466000.0,828640.0
257NC,1565200.0,NaN,NaN,12986000.0,12834000.0,924380.0,8424100.0,14458000.0,6358300.0,NaN,...,2909500.0,1163800.0,94882000.0,16770000.0,NaN,5269000.0,1992500.0,81933.0,4082100.0,221660.0
291NC,10190000.0,3492100.0,NaN,4763900.0,NaN,NaN,2931300.0,35289000.0,17571000.0,NaN,...,468820.0,NaN,742190.0,11032000.0,423920.0,NaN,NaN,NaN,465420.0,NaN
293NC,NaN,8980900.0,NaN,NaN,15985000.0,1266400.0,30161000.0,5597600.0,2562200.0,10683000.0,...,3816300.0,6648000.0,30074000.0,24812000.0,299370.0,4166800.0,2794200.0,549500.0,11231000.0,NaN
254NC,20403000.0,NaN,NaN,15211000.0,NaN,1223100.0,16635000.0,178520000.0,16453000.0,NaN,...,6284900.0,1036900.0,30095000.0,30851000.0,314740.0,422870.0,NaN,256490.0,3120700.0,1887300.0
302NC,46379000.0,4883200.0,NaN,8181600.0,7118500.0,838750.0,NaN,45673000.0,7536800.0,NaN,...,453110.0,NaN,16882000.0,15184000.0,16217000.0,NaN,NaN,NaN,1050400.0,4173800.0
221TC,NaN,6025900.0,2214600.0,9608100.0,NaN,2124000.0,33082000.0,70533000.0,4152900.0,NaN,...,8895400.0,11023000.0,4189600.0,13139000.0,4113700.0,NaN,NaN,759750.0,2372000.0,3720600.0
235TC,NaN,56819000.0,2318200.0,13024000.0,NaN,1421800.0,NaN,106960000.0,13834000.0,11738000.0,...,32703000.0,13953000.0,1227900.0,117170000.0,35485000.0,32323000.0,12168000.0,40872000.0,21619000.0,14283000.0
241TC,NaN,23928000.0,3559700.0,27617000.0,NaN,1825600.0,63729000.0,64641000.0,5750700.0,13259000.0,...,19246000.0,7578500.0,23887.0,22479000.0,165560000.0,11117000.0,15569000.0,16161000.0,27187000.0,7319700.0
254TC,NaN,11266000.0,3935600.0,48783000.0,37229000.0,4494200.0,128920000.0,188490000.0,17349000.0,30524000.0,...,23227000.0,72830000.0,1014300.0,86185000.0,102660000.0,19112000.0,116690000.0,38284000.0,28419000.0,16997000.0
257TC,NaN,19007000.0,7818500.0,27479000.0,NaN,2564500.0,118890000.0,54523000.0,20041000.0,16483000.0,...,31052000.0,16074000.0,NaN,148720000.0,364720000.0,9828400.0,14214000.0,40373000.0,26019000.0,47643000.0
293TC,NaN,NaN,2481400.0,14279000.0,NaN,NaN,50044000.0,295120000.0,17390000.0,NaN,...,3188300.0,7278200.0,NaN,13760000.0,373050000.0,334040.0,NaN,7365200.0,10401000.0,44325000.0
291TC,4254200.0,16086000.0,NaN,20028000.0,NaN,1476200.0,21192000.0,76157000.0,12473000.0,4133300.0,...,2467900.0,906160.0,NaN,20333000.0,53380000.0,NaN,6970400.0,5942800.0,17168000.0,8806700.0
302TC,2551500.0,43781000.0,NaN,33943000.0,8126500.0,1501100.0,139070000.0,108820000.0,NaN,22836000.0,...,20974000.0,12025000.0,2047200.0,33298000.0,92121000.0,24435000.0,14675000.0,50443000.0,27104000.0,10986000.0

# Data Cleaning

In [10]:
df = pd.DataFrame(data)
df.set_index('Gene ID', inplace=True)

In [11]:
# tc_columns = [col for col in df.columns if 'TC' in col]
# nc_columns = [col for col in df.columns if 'NC' in col]

# tc_data = df[tc_columns]
# nc_data = df[nc_columns]

In [12]:
# Count the number of non-NaN values for each row in TC and NC columns
non_nan_count_TC = df[[col for col in value_columns if "TC" in col]].count(axis=1)

# Identify rows with at least 6 non-NaN entries in TC columns
rows_to_keep = (non_nan_count_TC >= 6)

# Filter rows
tc_retain_df = df[rows_to_keep]
tc_columns = [col for col in tc_retain_df.columns if 'TC' in col]
tc_data = tc_retain_df[tc_columns]
tc_data

,221TC,235TC,241TC,254TC,257TC,293TC,291TC,302TC
Gene ID,,,,,,,,
GPNMB,6025900.0,56819000.0,23928000.0,11266000.0,19007000.0,NaN,16086000.0,43781000.0
SAE1,2214600.0,2318200.0,3559700.0,3935600.0,7818500.0,2481400.0,NaN,NaN
YP015,9608100.0,13024000.0,27617000.0,48783000.0,27479000.0,14279000.0,20028000.0,33943000.0
PPP1R12A,2124000.0,1421800.0,1825600.0,4494200.0,2564500.0,NaN,1476200.0,1501100.0
UTS2,33082000.0,NaN,63729000.0,128920000.0,118890000.0,50044000.0,21192000.0,139070000.0
...,...,...,...,...,...,...,...,...
ACO2,NaN,32323000.0,11117000.0,19112000.0,9828400.0,334040.0,NaN,24435000.0
CACYBP,NaN,12168000.0,15569000.0,116690000.0,14214000.0,NaN,6970400.0,14675000.0
RRBP1,759750.0,40872000.0,16161000.0,38284000.0,40373000.0,7365200.0,5942800.0,50443000.0
TLN1,2372000.0,21619000.0,27187000.0,28419000.0,26019000.0,10401000.0,17168000.0,27104000.0
EMILIN1,3720600.0,14283000.0,7319700.0,16997000.0,47643000.0,44325000.0,8806700.0,10986000.0

In [13]:
# Count the number of non-NaN values for each row in TC and NC columns
non_nan_count_NC = df[[col for col in value_columns if "NC" in col]].count(axis=1)

# Identify rows with at least 5 non-NaN entries in NC columns
rows_to_keep = (non_nan_count_NC >= 6)

# Filter rows
nc_retain_df = df[rows_to_keep]
nc_columns = [col for col in df.columns if 'NC' in col]
nc_data = nc_retain_df[nc_columns]
nc_data

,221NC,235NC,241NC,257NC,291NC,293NC,254NC,302NC
Gene ID,,,,,,,,
WFDC3,NaN,127000000.0,16615000.0,1565200.0,10190000.0,NaN,20403000.0,46379000.0
YP015,15431000.0,16334000.0,10241000.0,12986000.0,4763900.0,NaN,15211000.0,8181600.0
GCDH,12694000.0,19338000.0,8157200.0,12834000.0,NaN,15985000.0,NaN,7118500.0
PPP1R12A,2587100.0,1095900.0,988680.0,924380.0,NaN,1266400.0,1223100.0,838750.0
UTS2,31090000.0,17627000.0,9646800.0,8424100.0,2931300.0,30161000.0,16635000.0,NaN
...,...,...,...,...,...,...,...,...
TUBA1A,79390000.0,33000000.0,33499000.0,34195000.0,7058200.0,278550000.0,33236000.0,52515000.0
SERBP1,12371000.0,583440.0,NaN,2909500.0,468820.0,3816300.0,6284900.0,453110.0
PLIN4,152560000.0,83515000.0,42868000.0,94882000.0,742190.0,30074000.0,30095000.0,16882000.0
PARK7,53250000.0,10825000.0,16012000.0,16770000.0,11032000.0,24812000.0,30851000.0,15184000.0
TLN1,11239000.0,1373900.0,11466000.0,4082100.0,465420.0,11231000.0,3120700.0,1050400.0

In [14]:
# Initialize KNNImputer with the desired number of neighbors
knn_imputer = KNNImputer(n_neighbors=5)

# Convert the DataFrame to a NumPy array for imputation
data_tc_impute = tc_data.values

# Perform imputation
imputed_tc_data = knn_imputer.fit_transform(data_tc_impute)

# Convert the imputed values back to a DataFrame
imputed_tc_df = pd.DataFrame(imputed_tc_data, columns=tc_data.columns, index=tc_data.index)

# Display the final imputed DataFrame
imputed_tc_df

,221TC,235TC,241TC,254TC,257TC,293TC,291TC,302TC
Gene ID,,,,,,,,
GPNMB,6025900.0,56819000.0,23928000.0,11266000.0,19007000.0,6147520.0,16086000.0,43781000.0
SAE1,2214600.0,2318200.0,3559700.0,3935600.0,7818500.0,2481400.0,1148218.0,2566600.0
YP015,9608100.0,13024000.0,27617000.0,48783000.0,27479000.0,14279000.0,20028000.0,33943000.0
PPP1R12A,2124000.0,1421800.0,1825600.0,4494200.0,2564500.0,814686.0,1476200.0,1501100.0
UTS2,33082000.0,58307000.0,63729000.0,128920000.0,118890000.0,50044000.0,21192000.0,139070000.0
...,...,...,...,...,...,...,...,...
ACO2,3440220.0,32323000.0,11117000.0,19112000.0,9828400.0,334040.0,2639100.0,24435000.0
CACYBP,6237860.0,12168000.0,15569000.0,116690000.0,14214000.0,16945440.0,6970400.0,14675000.0
RRBP1,759750.0,40872000.0,16161000.0,38284000.0,40373000.0,7365200.0,5942800.0,50443000.0
TLN1,2372000.0,21619000.0,27187000.0,28419000.0,26019000.0,10401000.0,17168000.0,27104000.0
EMILIN1,3720600.0,14283000.0,7319700.0,16997000.0,47643000.0,44325000.0,8806700.0,10986000.0

In [15]:
# Initialize KNNImputer with the desired number of neighbors
knn_imputer = KNNImputer(n_neighbors=1)

# Convert the DataFrame to a NumPy array for imputation
data_nc_impute = nc_data.values

# Perform imputation
imputed_nc_data = knn_imputer.fit_transform(data_nc_impute)

# Convert the imputed values back to a DataFrame
imputed_nc_df = pd.DataFrame(imputed_nc_data, columns=nc_data.columns, index=nc_data.index)

# Display the final imputed DataFrame
imputed_nc_df

,221NC,235NC,241NC,257NC,291NC,293NC,254NC,302NC
Gene ID,,,,,,,,
WFDC3,8767900.0,127000000.0,16615000.0,1565200.0,10190000.0,6807700.0,20403000.0,46379000.0
YP015,15431000.0,16334000.0,10241000.0,12986000.0,4763900.0,15985000.0,15211000.0,8181600.0
GCDH,12694000.0,19338000.0,8157200.0,12834000.0,4763900.0,15985000.0,15211000.0,7118500.0
PPP1R12A,2587100.0,1095900.0,988680.0,924380.0,3924600.0,1266400.0,1223100.0,838750.0
UTS2,31090000.0,17627000.0,9646800.0,8424100.0,2931300.0,30161000.0,16635000.0,12868000.0
...,...,...,...,...,...,...,...,...
TUBA1A,79390000.0,33000000.0,33499000.0,34195000.0,7058200.0,278550000.0,33236000.0,52515000.0
SERBP1,12371000.0,583440.0,1163300.0,2909500.0,468820.0,3816300.0,6284900.0,453110.0
PLIN4,152560000.0,83515000.0,42868000.0,94882000.0,742190.0,30074000.0,30095000.0,16882000.0
PARK7,53250000.0,10825000.0,16012000.0,16770000.0,11032000.0,24812000.0,30851000.0,15184000.0
TLN1,11239000.0,1373900.0,11466000.0,4082100.0,465420.0,11231000.0,3120700.0,1050400.0

In [16]:
common_data = imputed_nc_df.merge(imputed_tc_df, left_index=True, right_index=True)
common_data = common_data.T
common_data

Gene ID,YP015,PPP1R12A,UTS2,USP29,IGLV3-19,CHD9,COL5A3,ALDH1L1,TNN,TTN,...,PLEC,PCBP1,TGFBI,DPYSL2,EEF1A1P5,H2AC18,TUBA1A,SERBP1,PARK7,TLN1
221NC,15431000.0,2587100.0,31090000.0,141350000.0,5217900.0,337700000.0,20982000.0,150840000.0,26858000.0,1.993900e+09,...,2114000.0,21151000.0,663230.0,13258000.0,2.412600e+08,9.231300e+08,79390000.0,12371000.0,53250000.0,11239000.0
235NC,16334000.0,1095900.0,17627000.0,11587000.0,10646000.0,53950000.0,3793500.0,104910000.0,71468000.0,3.842200e+08,...,576310.0,8976800.0,954650.0,999830.0,6.552400e+07,1.803200e+08,33000000.0,583440.0,10825000.0,1373900.0
241NC,10241000.0,988680.0,9646800.0,51832000.0,23535000.0,398900000.0,8825100.0,128890000.0,50164000.0,5.539800e+08,...,148130.0,8299800.0,10411000.0,6435000.0,5.450900e+07,3.870800e+08,33499000.0,1163300.0,16012000.0,11466000.0
257NC,12986000.0,924380.0,8424100.0,14458000.0,6358300.0,143530000.0,12030000.0,61167000.0,8385800.0,5.827000e+08,...,3427400.0,4081800.0,772370.0,10410000.0,5.578800e+07,5.070100e+08,34195000.0,2909500.0,16770000.0,4082100.0
291NC,4763900.0,3924600.0,2931300.0,35289000.0,17571000.0,220840000.0,2684800.0,79790000.0,42360000.0,4.120200e+08,...,215220.0,5248400.0,5577400.0,5512000.0,1.150200e+07,2.271300e+08,7058200.0,468820.0,11032000.0,465420.0
293NC,15985000.0,1266400.0,30161000.0,5597600.0,2562200.0,33940000.0,2661400.0,21892000.0,6196700.0,8.617100e+07,...,9491600.0,21056000.0,3084500.0,64045000.0,2.271200e+08,4.487600e+08,278550000.0,3816300.0,24812000.0,11231000.0
254NC,15211000.0,1223100.0,16635000.0,178520000.0,16453000.0,689260000.0,11374000.0,145280000.0,44870000.0,1.234000e+08,...,1687900.0,7933500.0,5473100.0,12404000.0,9.809000e+07,1.247500e+09,33236000.0,6284900.0,30851000.0,3120700.0
302NC,8181600.0,838750.0,12868000.0,45673000.0,7536800.0,398530000.0,6318700.0,50233000.0,24827000.0,1.419700e+09,...,249990.0,7212900.0,7051500.0,17360000.0,4.753900e+07,3.811400e+08,52515000.0,453110.0,15184000.0,1050400.0
221TC,9608100.0,2124000.0,33082000.0,70533000.0,4152900.0,843660000.0,10694000.0,92569000.0,20916000.0,2.641500e+08,...,2765900.0,12259000.0,4698500.0,3408800.0,1.391900e+08,5.251700e+08,47491000.0,8895400.0,13139000.0,2372000.0
235TC,13024000.0,1421800.0,58307000.0,106960000.0,13834000.0,226970000.0,4083700.0,40591000.0,33852000.0,2.997600e+07,...,44014000.0,82044000.0,24896000.0,16892000.0,6.264600e+08,1.524800e+09,289310000.0,32703000.0,117170000.0,21619000.0
241TC,27617000.0,1825600.0,63729000.0,64641000.0,5750700.0,100860000.0,3460680.0,29617000.0,27318000.0,4.151200e+08,...,34035000.0,106980000.0,49026000.0,36100000.0,9.128200e+08,2.105500e+09,686430000.0,19246000.0,22479000.0,27187000.0
254TC,48783000.0,4494200.0,128920000.0,188490000.0,17349000.0,219170000.0,8201800.0,72552000.0,21872000.0,1.979900e+08,...,40244000.0,78532000.0,47036000.0,34491000.0,1.575200e+09,5.030600e+09,947780000.0,23227000.0,86185000.0,28419000.0
257TC,27479000.0,2564500.0,118890000.0,54523000.0,20041000.0,123010000.0,3445900.0,17268000.0,56481000.0,4.668100e+07,...,97493000.0,80332000.0,172250000.0,43879000.0,7.175200e+08,3.002400e+09,616020000.0,31052000.0,148720000.0,26019000.0
293TC,14279000.0,814686.0,50044000.0,295120000.0,17390000.0,205540000.0,7161400.0,51288000.0,54582000.0,1.445200e+07,...,14720000.0,22672000.0,354230000.0,8575100.0,2.101600e+08,4.597300e+08,159450000.0,3188300.0,13760000.0,10401000.0
291TC,20028000.0,1476200.0,21192000.0,76157000.0,12473000.0,284240000.0,6641900.0,76579000.0,51804000.0,4.255600e+08,...,11813000.0,30408000.0,36009000.0,12003000.0,2.058900e+08,1.308200e+09,138680000.0,2467900.0,20333000.0,17168000.0
302TC,33943000.0,1501100.0,139070000.0,108820000.0,23913220.0,332100000.0,4755700.0,58531000.0,23931000.0,5.807400e+08,...,36603000.0,129890000.0,47959000.0,14890000.0,8.788600e+08,2.439100e+09,457230000.0,20974000.0,33298000.0,27104000.0